echo '<div class="col-sm-9 padding-right">';
					echo '<div class="product-details"><!--product-details-->';
						echo '<div class="col-sm-5">';
							echo '<div class="view-product">';
								echo "<img src="images/product-details/1.jpg" alt="" />";
							echo "</div>";

						echo "</div>";
						echo "<div class="col-sm-7">";
							echo "<div class="product-information"><!--/product-information-->";
								echo "<img src="" class="newarrival" alt="" />";
								echo "<h2>Anne Klein Sleeveless Colorblock Scuba</h2>";
								echo "<p>Web ID: 1089772</p>";
								echo "<img src="images/product-details/rating.png" alt="" />";
								echo "<span>";
									echo "<span>US $59</span>";
									echo "<label>Quantity:</label>";
									echo "<input type="text" value="3" />";
									echo "<button type="button" class="btn btn-fefault cart">";
										echo "<i class="fa fa-shopping-cart"></i>";
										echo "Add to cart";
									echo "</button>";
								echo "</span>";
								echo "<p><b>Availability:</b> In Stock</p>";
								echo "<p><b>Condition:</b> New</p>";
								echo "<p><b>Brand:</b> E-SHOPPER</p>";
								echo "<a href=""><img src="images/product-details/share.png" class="share img-responsive"  alt="" /></a>";
							echo "</div><!--/product-information-->";
						echo "</div>";
					echo "</div><!--/product-details-->";
				
				echo "</div>";